### ISSUE TITLE
Deployment script fails if transaction is not mined in 50 blocks

### ISSUE THREAD

**Issue by alpeshvmodi** [OpenSTFoundation/openst-platform#11]
Presently the deployment fails when the mining is not done in 50 blocks. On Ropsten and Main net, this will be a issue as it is not guaranteed that the mining will happen in a certain period of time.

**Comment by kedarchandrayan** [comment]
For Ropsten and Main net, this is a major issue as every later step will fail if some step exits in error.

**Comment by kedarchandrayan** [comment]
We will add safeDeploy in deploy helper, which returns a promise which resolves when transaction hash is obtained and then polls for receipt after this. This way the deployment script does not exit in error.

**Comment by kedarchandrayan** [comment]
New deployments are using safe deploy method which are not dependent on the 50 block timeout which web3 imposes for mining of the transaction.

**Comment by kedarchandrayan** [comment]
Closing this issue.
