### ISSUE TITLE
Introduce connection pooling when connecting to GETH

### ISSUE THREAD

**Issue by kedarchandrayan** [OpenSTFoundation/openst-platform#148]
openst-base has a implementation for web3 connection pooling wherein multiple number of connections are made with the GETH server and these connections are used in a round robin manner.

This number of connections is governed by the environment variable - OST_WEB3_POOL_SIZE

We need to make use of this pooling functionality from openst-base in openst-platform.

Pooling would allow us to use a Web3Provider from a pool of providers and would save some time spent in creating a new provider everytime it is needed. Also, if a provider goes down unexpectedly, pooling would save the time required to create a new provider and choose another provider instance from the pool.

**Comment by shlokgilda** [comment]
Closing this issue as solved in PR #149 .
