### ISSUE TITLE
figure out redeployment as config.json has member info which will be overwritten

### ISSUE THREAD

**Issue by kedarchandrayan** [OpenSTFoundation/openst-platform#30]
Presently after every code deploy the config.json is erased. Also this can't be committed to code for security reasons and also this file will be different for different environments.

**Comment by bala007** [comment]
Not sure where you guys storing this file.
If you are storing it in app root folder, then it will get overwritten by new build.
For the first version you can try to write it into the shared folder, where it will still be there even after redeployment of new builds.

**Comment by rachinkapoor** [comment]
@bala007 
The API now reads config.json file using the OST_MEMBER_CONFIG_FILE_PATH env variable.
We also need to preserve transaction logs. The directory path where these logs will be stored is read using OST_TRANSACTION_LOGS_FOLDER env variable.

cc: @puneet-khushwani-eth
