### ISSUE TITLE
Look for the manual of openst-platform

### ISSUE THREAD

**Issue by zhazha3374** [OpenSTFoundation/openst-platform#82]
Hi, everyone. I want to create a running environment of  the openst-platform for study & test.  What manual can I refer to?  Thanks for your advice.

**Comment by benjaminbollen** [comment]
referencing #83 
the reproduction steps are in the readme file in the `/test` folder; we'll follow up on issue 83.

https://github.com/OpenSTFoundation/openst-platform/blob/master/test/README.md
