### ISSUE TITLE
Error: This contract object doesn\'t have address set yet, please set an address first.

### ISSUE THREAD

**Issue by zhazha3374** [OpenSTFoundation/openst-platform#83]
Hi, everyone. 
I built the openst-platform by README.md (https://github.com/OpenSTFoundation/openst-platform/blob/master/test/README.md). 

At the step "Stake Simple Tokens on value chain to mint Branded Tokens, In Terminal 1:", when I executed the command " > node services/inter_comm/stake_and_mint.js",  A error occurred.
    
     throw new Error('This contract object doesn\'t have address set yet, please set an address first.');
                                                                                                                                    ^
How do I set an address?

**Comment by jasonklein** [comment]
@zhazha3374: when you respond to the prompts, "Do you want to proceed? [Y/N]", do you enter in 'y' or 'Y'? Lowercase 'y' is not currently an affirmative response, but I have just made #84 to address that.

Try using uppercase 'Y' and let us know whether that resolves the issue.

**Comment by zhazha3374** [comment]
@jasonklein Thanks for your reply. After I used the uppercase 'Y', the issue disappeared.

Now, I'm studying the section "Time to start playing with OpenST Restful APIs!". After ran the command "npm start", how to use Postman for Restful APIs (optional)? I means how to import OpenST routes..., how to import environment variables..., how to modify the imported environment variables... etc. Is there a manual for these steps?

**Comment by jasonklein** [comment]
@zhazha3374: please refer to #89 for your questions about following the given API steps.

Closing this issue as the first question has been resolved.
