### ISSUE TITLE
Is the branded token unlimited?

### ISSUE THREAD

**Issue by zhazha3374** [OpenSTFoundation/openst-platform#87]
Hi, everyone. The amount of branded token [BT] is unlimited? For example, if I stake 1000 simple token [ST], how many amount of BT should mint?   10000BT or 100000BT or more?

**Comment by maxmehlbaum** [comment]
do u have the platform running? if so can u help me get started?

**Comment by jasonklein** [comment]
@zhazha3374, the amount of branded tokens that will be minted is based on the `conversionRate` for the branded token. Staking 1000 Simple Tokens for a branded token with a `conversionRate` of 2 will mint 2000 branded tokens; for a branded token with a `conversionRate` of 10, 10000 branded tokens will be minted.

**Comment by jasonklein** [comment]
@maxmehlbaum, you can follow the instructions here to connect to the OpenST utility chain: https://github.com/OpenSTFoundation/openst-platform/blob/v0.9.1/CHANGELOG.md#openst-platform-v091-december-19-2017.

If you find there are errors in that or you have any questions, feel free to ask in another issue or reach out to us in our gitter channel: https://gitter.im/OpenSTFoundation/SimpleToken

Closing this issue.
