### ISSUE TITLE
./run_value_chain.js no file or directory 

### ISSUE THREAD

**Issue by maxmehlbaum** [OpenSTFoundation/openst-platform#88]
when I run this command under the test path it states that no such directory exists. also if anyone can help me get started with the process of creating your own token through Simple token it would be much appreciated

**Comment by jasonklein** [comment]
@maxmehlbaum: are you typing `./run_value_chain.sh` or `./run_value_chain.js`? The latter, with the extension "js", is incorrect.

**Comment by jasonklein** [comment]
Closing this as #91 was opened with additional troubleshooting details.
