### ISSUE TITLE
 No such file or directory is found when i type in both the test and openstplatform paths source test/open_st_env_vars.sh

### ISSUE THREAD

**Issue by maxmehlbaum** [OpenSTFoundation/openst-platform#90]
im stuck on this step:

In Terminal 1:
Start the stake and mint intercom process while branded tokens are minted (NOTE: This process need to be running till Terminal 2 process ends)
  > cd openst-platform
  > source test/open_st_env_vars.sh
  > node services/inter_comm/stake_and_mint.js

im in the openst-platfrom

i type in source test/open_st_env_vars.sh

and nothing shows up

i then inspect the terminal processes and see that 

# just covers private information that i was given 
Using Original Simple Token Contract
OpenStUtilityContractInteract :: contractAddress ###############
 Creating new member account 
 Address ::  #################3 Passphrase ::  testtest 
 New Member company address ::  ##################
 New member config defaults generated. { Reserve: '###################',
  Symbol: 'ACME',
  Route: '/acme',
  ApiAuth: { users: { acme: 'acmesecret' } },
  Callback: 'http://localhost:9000' } 
Updating Config File: /Users/max/Downloads/openst-platform-master/config.json
Config file updated!
 member.Reserve: ##################
 Fetch Address balance on ValueChain 
 Failed to fund  Address 

it says here fetch address balance on value chain 

but when i go to the value chain terminal i receive 
Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use

might try to retry the whole thing

**Comment by jasonklein** [comment]
@maxmehlbaum: you can see here, on GH, that `test/open_st_env_vars.sh` exists. You should have that file locally—if it is there but your terminal says no such file or directory, then I suspect you may not be in the correct directory.

Can you clarify what you mean by "stuck"? The output provided should have come from executing `./run_complete_test_deploy.sh` and not from `node services/inter_comm/stake_and_mint.js`. Could you also re-provide that output but without any redactions?

Notwithstanding the above, can you let us know if retrying was successful?

**Comment by maxmehlbaum** [comment]
yes you were right, I put more in depth steps on GitHub if you could check it out I believe it will help get down to it.


thanks,


max

________________________________

**Comment by jasonklein** [comment]
Closing this as #91 was opened with additional troubleshooting details.
