### ISSUE TITLE
Failed to unlock Reserve

### ISSUE THREAD

**Issue by yaja95** [OpenSTFoundation/openst-platform#95]
Upon performing the terminal 4 step: 

> cd openst-platform
  > source test/open_st_env_vars.sh
  > node tools/stake_and_mint/for_branded_token.js
  Note: ACME key password is "testtest"

The following appears:

Welcome to Staking And Minting Tool 
 Please choose member to fund. 
1 ' for ' 'Acme Coin' '(' 'ACME' ')'
2 ' for ' 'Acme Coin' '(' 'ACME' ')'

I then choose 1

The terminal displays:

Confirm Member 
 Please Confirm these details. 
Name :: Acme Coin

I choose yes

This is then displayed: 

Acme Coin has 100 ST 
Please mention the Simple Tokens to Assign.

I assign an arbitrary amount less than 100

I then get: 

Validate Stake Contract 
 Please provide member reserve passphrase. 
Passphrase:

I enter testtest

And I receive the following output:
  Unlocking Member Reserve on ValueChain 
 Failed to unlock reserve. 
 Returned error: no key for given address or file 
 Please provide correct member reserve passphrase.  

I'm not sure what the problem is because when the new member account is created, 
the passphrase it gives it testtest.

Creating new member account 
 Address ::  ******************** Passphrase ::  testtest

**Comment by kedarchandrayan** [comment]
We have changed the deployment and on boarding process and the sample scripts. This issue is now resolved. Code is available in develop branch and will be merged to master branch soon.
